[default.variables]
# GTK
gtk_accent           = "#E06C75"
gtk_error            = "#E06C75"
gtk_success          = "#98C379"
gtk_text             = "#ABB2BF"
gtk_bg_popup         = "#3E4451"
gtk_bg               = "#282C34"
gtk_bg_destructive   = "#E06C75"

# Statusline
prompt_normal_mode       = "#98C379"
prompt_insert_mode       = "#61AFEF"
prompt_visual_mode       = "#C678DD"
prompt_replacement_mode  = "#E06C75"
prompt_unknown_mode      = "#E5C07B"
prompt_error             = "#E06C75"
prompt_detached_branch   = "#C678DD"
prompt_branch            = "#98C379"
prompt_commit            = "#61AFEF"
prompt_action            = "#E5C07B"
prompt_ssh_host          = "#C678DD"
prompt_ssh_user          = "#61AFEF"
prompt_venv              = "#98C379"
prompt_user              = "#282C34"
prompt_root              = "#E06C75"
prompt_pwd               = "#5C6370"

# Status icons
status_ahead             = "#61AFEF"
status_behind            = "#E06C75"
status_stashed           = "#C678DD"
status_added             = "#98C379"
status_deleted           = "#E06C75"
status_modified          = "#E5C07B"
status_renamed           = "#61AFEF"
status_unmerged          = "#E06C75"
status_untracked         = "#5C6370"
foreground_text          = "#ABB2BF"

# Fish shell
color_autosuggestion           = "#828997"
color_command                  = "#61AFEF"
color_comment                  = "#828997"
color_cwd                      = "#98C379"
color_cwd_root                 = "#E06C75"
color_end                      = "#E5C07B"
color_error                    = "#E06C75"
color_escape                   = "#56B6C2"
color_host                     = "#3E4451"
color_host_remote              = "#E5C07B"
color_normal                   = "#ABB2BF"
color_operator                 = "#C678DD"
color_param                    = "#E5C07B"
color_quote                    = "#98C379"
color_redirection_color        = "#56B6C2"
color_search_match_foreground  = "#282C34"
color_search_match_background  = "#E5C07B"
color_selection_foreground     = "#282C34"
color_selection_background     = "#3E4451"
color_status                   = "#E06C75"
color_user                     = "#61AFEF"
pager_color_completion         = "#ABB2BF"
pager_color_description_color  = "#828997"
pager_color_prefix_color       = "#3E4451"
pager_color_progress_background= "#3E4451"
pager_color_progress_foreground= "#ABB2BF"

# Niri
active-color   = "#61AFEF"
inactive-color = "#1C1F26"
urgent-color   = "#E06C75"
shadow         = "#1C1F26"

# Cursor
foreground = "#ABB2BF"
outline    = "#3E4451"
background = "#528BFF"

# SDDM / login
accent_warning   = "#D19A66"
accent_info      = "#56B6C2"
accent_primary   = "#61AFEF"
accent_secondary = "#98C379"
accent_light     = "#EAEAEA"
accent_hover     = "#C678DD"
accent_alt       = "#E06C75"
error       = "#E06C75"
error_alt   = "#E06C75"
warning     = "#D19A66"
attention   = "#D19A66"
success     = "#98C379"
info        = "#56B6C2"
link        = "#61AFEF"

# Foreground layers
fg_primary         = "#ABB2BF"
fg_secondary       = "#828997"
fg_muted           = "#5C6370"
fg_overlay_strong  = "#4B5263"
fg_overlay_medium  = "#3E4451"
fg_overlay_weak    = "#2C313C"

# Background layers
bg_surface_high    = "#3E4451"
bg_surface_medium  = "#282C34"
bg_surface_low     = "#21252B"
bg_base            = "#282C34"
bg_subtle          = "#1C1F26"
bg_deep            = "#181A1F"

