[default.variables]
#mako
mako_background = "#191724"
mako_border = "#ebbcba"
mako_low = "#9ccfd8"
mako_normal = "#f6c177"
mako_high = "#eb6f92"

# GTK
gtk_accent           = "#ebbcba"
gtk_error            = "#eb6f92"
gtk_success          = "#56949f"
gtk_text             = "#e0def4"
gtk_bg_popup         = "#232136"
gtk_bg               = "#191724"
gtk_bg_destructive   = "#232136"

# Statusline
prompt_normal_mode       = "#56949f"
prompt_insert_mode       = "#ebbcba"
prompt_visual_mode       = "#9ccfd8"
prompt_replacement_mode  = "#f6c177"
prompt_unknown_mode      = "#eb6f92"
prompt_error             = "#eb6f92"
prompt_detached_branch   = "#c4a7e7"
prompt_branch            = "#ebbcba"
prompt_commit            = "#ebbcba"
prompt_action            = "#9ccfd8"
prompt_ssh_host          = "#c4a7e7"
prompt_ssh_user          = "#ebbcba"
prompt_venv              = "#ebbcba"
prompt_user              = "#ebbcba"
prompt_root              = "#f6c177"
prompt_pwd               = "#ebbcba"

# Status icons
status_ahead             = "#ea9a97"
status_behind            = "#9ccfd8"
status_stashed           = "#9ccfd8"
status_added             = "#ea9a97"
status_deleted           = "#ea9a97"
status_modified          = "#ea9a97"
status_renamed           = "#c4a7e7"
status_unmerged          = "#f6c177"
status_untracked         = "#ea9a97"
foreground_text          = "#575279"

# Fish shell
color_autosuggestion           = "#575279"
color_command                  = "#ea9a97"
color_comment                  = "#575279"
color_cwd                      = "#ea9a97"
color_cwd_root                 = "#c4a7e7"
color_end                      = "#ea9a97"
color_error                    = "#eb6f92"
color_escape                   = "#9ccfd8"
color_host                     = "#9ccfd8"
color_host_remote              = "#f6c177"
color_normal                   = "#e0def4"
color_operator                 = "#ea9a97"
color_param                    = "#ea9a97"
color_quote                    = "#c4a7e7"
color_redirection_color        = "#c4a7e7"
color_search_match_foreground  = "#c4a7e7"
color_search_match_background  = "#ea9d34"
color_selection_foreground     = "#c4a7e7"
color_selection_background     = "#ea9d34"
color_status                   = "#9ccfd8"
color_user                     = "#ebbcba"
pager_color_completion         = "#e0def4"
pager_color_description_color  = "#575279"
pager_color_prefix_color       = "#575279"
pager_color_progress_background= "#ea9d34"
pager_color_progress_foreground= "#c4a7e7"

# Niri
active-color   = "#ebbcba"
inactive-color = "#232136"
urgent-color   = "#f6c177"
shadow         = "#232136"

# Cursor
foreground = "#ebbcba"
outline    = "#524f67"
background = "#ea9d34"

# SDDM / login
accent_warning   = "#f6c177"
accent_info      = "#9ccfd8"
accent_primary   = "#ebbcba"
accent_secondary = "#ebbcba"
accent_light     = "#c4a7e7"
accent_hover     = "#ea9a97"
accent_alt       = "#ebbcba"
error       = "#eb6f92"
error_alt   = "#eb6f92"
warning     = "#f6c177"
attention   = "#9ccfd8"
success     = "#56949f"
info        = "#9ccfd8"
link        = "#c4a7e7"

# Foreground layers
fg_primary         = "#faf4ed"
fg_secondary       = "#faf4ed"
fg_muted           = "#fffaf3"
fg_overlay_strong  = "#fffaf3"
fg_overlay_medium  = "#fffaf3"
fg_overlay_weak    = "#fffaf3"

# Background layers
bg_surface_high    = "#191724"
bg_surface_medium  = "#232136"
bg_surface_low     = "#232136"
bg_base            = "#191724"
bg_subtle          = "#191724"
bg_deep            = "#191724"
