[default.variables]
#mako
mako_background = "@background"
mako_border = "#fab387"
mako_low = "#fab387"
mako_normal = "#eba0ac"
mako_high = "#f38ba8"

# GTK
gtk_accent           = "#89b4fa"
gtk_error            = "#f38ba8"
gtk_success          = "@success@"
gtk_text             = "#cdd6f4"
gtk_bg_popup         = "#bac2de"
gtk_bg               = "#181825"
gtk_bg_destructive   = "#bac2de"

# Statusline
prompt_normal_mode       = "#a6e3a1"
prompt_insert_mode       = "#89b4fa"
prompt_visual_mode       = "#fab387"
prompt_replacement_mode  = "#eba0ac"
prompt_unknown_mode      = "#f38ba8"
prompt_error             = "#f38ba8"
prompt_detached_branch   = "#89dceb"
prompt_branch            = "#fab387"
prompt_commit            = "#89b4fa"
prompt_action            = "#fab387"
prompt_ssh_host          = "#89dceb"
prompt_ssh_user          = "#89b4fa"
prompt_venv              = "#fab387"
prompt_user              = "#89b4fa"
prompt_root              = "#eba0ac"
prompt_pwd               = "#89b4fa"

# Status icons
status_ahead             = "#b4befe"
status_behind            = "#fab387"
status_stashed           = "#fab387"
status_added             = "#f9e2af"
status_deleted           = "#f9e2af"
status_modified          = "#f9e2af"
status_renamed           = "#94e2d5"
status_unmerged          = "#eba0ac"
status_untracked         = "#b4befe"
foreground_text          = "#1e1e2e"

# Fish shell
color_autosuggestion           = "#cdd6f4"
color_command                  = "#f9e2af"
color_comment                  = "#cdd6f4"
color_cwd                      = "#b4befe"
color_cwd_root                 = "#94e2d5"
color_end                      = "#f9e2af"
color_error                    = "#f38ba8"
color_escape                   = "#fab387"
color_host                     = "#fab387"
color_host_remote              = "#eba0ac"
color_normal                   = "#cdd6f4"
color_operator                 = "#f9e2af"
color_param                    = "#f9e2af"
color_quote                    = "#94e2d5"
color_redirection_color        = "#89dceb"
color_search_match_foreground  = "#89dceb"
color_search_match_background  = "#89dceb"
color_selection_foreground     = "#89dceb"
color_selection_background     = "#89dceb"
color_status                   = "#fab387"
color_user                     = "#89b4fa"
pager_color_completion         = "#cdd6f4"
pager_color_description_color  = "#cdd6f4"
pager_color_prefix_color       = "#cdd6f4"
pager_color_progress_background= "#89dceb"
pager_color_progress_foreground= "#89dceb"

# Niri
active-color   = "#89b4fa"
inactive-color = "#313244"
urgent-color   = "#eba0ac"
shadow         = "#313244"

# Cursor
foreground = "#b4befe"
outline    = "#11111b"
background = "#cdd6f4"

# SDDM / login
accent_warning   = "#eba0ac"
accent_info      = "#fab387"
accent_primary   = "#89b4fa"
accent_secondary = "#fab387"
accent_light     = "#89dceb"
accent_hover     = "#b4befe"
accent_alt       = "#fab387"
error       = "#f38ba8"
error_alt   = "#f38ba8"
warning     = "#eba0ac"
attention   = "#fab387"
success     = "@success@"
info        = "#fab387"
link        = "#89dceb"

# Foreground layers
fg_primary         = "#bac2de"
fg_secondary       = "#bac2de"
fg_muted           = "#bac2de"
fg_overlay_strong  = "#bac2de"
fg_overlay_medium  = "#bac2de"
fg_overlay_weak    = "#bac2de"

# Background layers
bg_surface_high    = "#181825"
bg_surface_medium  = "#313244"
bg_surface_low     = "#313244"
bg_base            = "#181825"
bg_subtle          = "#181825"
bg_deep            = "#181825"

