[default.variables]
#mako
mako_background = "@background"
mako_border = "@secondary@"
mako_low = "@info@"
mako_normal = "@warning@"
mako_high = "@error@"

# GTK
gtk_accent           = "@primary@"
gtk_error            = "@error@"
gtk_success          = "@success@"
gtk_text             = "@text@"
gtk_bg_popup         = "@foreground@"
gtk_bg               = "@background@"
gtk_bg_destructive   = "@foreground@"

# Statusline
prompt_normal_mode       = "@succes@"
prompt_insert_mode       = "@primary@"
prompt_visual_mode       = "@info@"
prompt_replacement_mode  = "@warning@"
prompt_unknown_mode      = "@error@"
prompt_error             = "@error@"
prompt_detached_branch   = "@tertiary@"
prompt_branch            = "@secondary@"
prompt_commit            = "@primary@"
prompt_action            = "@info@"
prompt_ssh_host          = "@tertiary@"
prompt_ssh_user          = "@primary@"
prompt_venv              = "@secondary@"
prompt_user              = "@primary@"
prompt_root              = "@warning@"
prompt_pwd               = "@primary@"

# Status icons
status_ahead             = "@muted_primary@"
status_behind            = "@info@"
status_stashed           = "@info@"
status_added             = "@muted_secondary@"
status_deleted           = "@muted_secondary@"
status_modified          = "@muted_secondary@"
status_renamed           = "@muted_tertiary@"
status_unmerged          = "@warning@"
status_untracked         = "@muted_primary@"
foreground_text          = "@text@"

# Fish shell
color_autosuggestion           = "@subtext@"
color_command                  = "@muted_secondary@"
color_comment                  = "@subtext@"
color_cwd                      = "@muted_primary@"
color_cwd_root                 = "@muted_tertiary@"
color_end                      = "@muted_secondary@"
color_error                    = "@error@"
color_escape                   = "@info@"
color_host                     = "@info@"
color_host_remote              = "@warning@"
color_normal                   = "@text@"
color_operator                 = "@muted_secondary@"
color_param                    = "@muted_secondary@"
color_quote                    = "@muted_tertiary@"
color_redirection_color        = "@tertiary@"
color_search_match_foreground  = "@tertiary@"
color_search_match_background  = "@highlight@"
color_selection_foreground     = "@tertiary@"
color_selection_background     = "@highlight@"
color_status                   = "@info@"
color_user                     = "@primary@"
pager_color_completion         = "@text@"
pager_color_description_color  = "@subtext@"
pager_color_prefix_color       = "@subtext@"
pager_color_progress_background= "@highlight@"
pager_color_progress_foreground= "@tertiary@"

# Niri
active-color   = "@primary@"
inactive-color = "@muted_background@"
urgent-color   = "@warning@"
shadow         = "@muted_background@"

# Cursor
foreground = "@cursor_foreground@"
outline    = "@cursor_outline@"
background = "@cursor_background@"

# SDDM / login
accent_warning   = "@warning@"
accent_info      = "@info@"
accent_primary   = "@primary@"
accent_secondary = "@secondary@"
accent_light     = "@tertiary@"
accent_hover     = "@muted_primary@"
accent_alt       = "@secondary@"
error       = "@error@"
error_alt   = "@error@"
warning     = "@warning@"
attention   = "@info@"
success     = "@success@"
info        = "@info@"
link        = "@tertiary@"

# Foreground layers
fg_primary         = "@primary@"
fg_secondary       = "@secondary@"
fg_muted           = "@muted_foreground@"
fg_overlay_strong  = "@muted_foreground@"
fg_overlay_medium  = "@muted_foreground@"
fg_overlay_weak    = "@muted_foreground@"

# Background layers
bg_surface_high    = "@background@"
bg_surface_medium  = "@muted_background@"
bg_surface_low     = "@muted_background@"
bg_base            = "@background@"
bg_subtle          = "@background@"
bg_deep            = "@background@"

