[default.variables]
# GTK
gtk_accent           = "@color_error@"
gtk_error            = "@color_error@"
gtk_success          = "@color_secondary@"
gtk_text             = "@color_text@"
gtk_bg_popup         = "@color_popup@"
gtk_bg               = "@color_background@"
gtk_bg_destructive   = "@color_error@"

# Statusline
prompt_normal_mode       = "@color_secondary@"
prompt_insert_mode       = "@color_primary@"
prompt_visual_mode       = "@color_tertiary@"
prompt_replacement_mode  = "@color_error@"
prompt_unknown_mode      = "@color_warning@"
prompt_error             = "@color_error@"
prompt_detached_branch   = "@color_tertiary@"
prompt_branch            = "@color_secondary@"
prompt_commit            = "@color_primary@"
prompt_action            = "@color_warning@"
prompt_ssh_host          = "@color_tertiary@"
prompt_ssh_user          = "@color_primary@"
prompt_venv              = "@color_secondary@"
prompt_user              = "@color_background@"
prompt_root              = "@color_error@"
prompt_pwd               = "@color_muted@"

# Status icons
status_ahead             = "@color_primary@"
status_behind            = "@color_error@"
status_stashed           = "@color_tertiary@"
status_added             = "@color_secondary@"
status_deleted           = "@color_error@"
status_modified          = "@color_warning@"
status_renamed           = "@color_primary@"
status_unmerged          = "@color_error@"
status_untracked         = "@color_muted@"
foreground_text          = "@color_text@"

# Fish shell
color_autosuggestion           = "@color_subtext@"
color_command                  = "@color_primary@"
color_comment                  = "@color_subtext@"
color_cwd                      = "@color_secondary@"
color_cwd_root                 = "@color_error@"
color_end                      = "@color_warning@"
color_error                    = "@color_error@"
color_escape                   = "@color_info@"
color_host                     = "@color_highlight@"
color_host_remote              = "@color_warning@"
color_normal                   = "@color_text@"
color_operator                 = "@color_tertiary@"
color_param                    = "@color_warning@"
color_quote                    = "@color_secondary@"
color_redirection_color        = "@color_info@"
color_search_match_foreground  = "@color_background@"
color_search_match_background  = "@color_warning@"
color_selection_foreground     = "@color_background@"
color_selection_background     = "@color_highlight@"
color_status                   = "@color_error@"
color_user                     = "@color_primary@"
pager_color_completion         = "@color_text@"
pager_color_description_color  = "@color_subtext@"
pager_color_prefix_color       = "@color_highlight@"
pager_color_progress_background= "@color_popup@"
pager_color_progress_foreground= "@color_text@"

# Niri
active-color   = "@color_primary@"
inactive-color = "@color_shadow@"
urgent-color   = "@color_error@"
shadow         = "@color_shadow@"

# Cursor
foreground = "@cursor_foreground@"
outline    = "@cursor_outline@"
background = "@cursor_background@"

# SDDM / login
accent_warning   = "@accent_warning@"
accent_info      = "@accent_info@"
accent_primary   = "@accent_link@"
accent_secondary = "@accent_success@"
accent_light     = "@accent_light@"
accent_hover     = "@accent_hover@"
accent_alt       = "@accent_error@"
error       = "@accent_error@"
error_alt   = "@accent_error@"
warning     = "@accent_warning@"
attention   = "@accent_warning@"
success     = "@accent_success@"
info        = "@accent_info@"
link        = "@accent_link@"

# Foreground layers
fg_primary         = "@fg_primary@"
fg_secondary       = "@fg_secondary@"
fg_muted           = "@fg_muted@"
fg_overlay_strong  = "@fg_overlay_strong@"
fg_overlay_medium  = "@fg_overlay_medium@"
fg_overlay_weak    = "@fg_overlay_weak@"

# Background layers
bg_surface_high    = "@bg_high@"
bg_surface_medium  = "@bg_medium@"
bg_surface_low     = "@bg_low@"
bg_base            = "@bg_medium@"
bg_subtle          = "@bg_subtle@"
bg_deep            = "@bg_deep@"

