# Core roles
color_primary       = "#465CA8"
color_secondary     = "#026374"
color_tertiary      = "#034F9E"
color_warning       = "#EE5E85"
color_error         = "#CE0B43"
color_info          = "#704998"
color_muted         = "#39598A"
color_text          = "#111015"
color_subtext       = "#465656"
color_background    = "#667886"
color_popup         = "#ABC929"
color_surface       = "#8A9BB9"
color_highlight     = "#DAD650"
color_shadow        = "#503424"

# Cursor
cursor_foreground   = "#0196D5"
cursor_background   = "#FFFFFF"
cursor_outline      = "#121116"

# Accentear
accent_warning      =  "#EE5E85"
accent_info         =  "#704998"
accent_link         = "#0093D3"
accent_success      = "#8DB324"
accent_hover        = "#31527D"
accent_error        = "#E83D2B"
accent_light        = "#024F9D"

# Foreground layers
fg_primary          = "#6E4796"
fg_secondary        = "#4056A2"
fg_muted            = "#4157A3"
fg_overlay_strong   = "#006C6E"
fg_overlay_medium   = "#058F99"
fg_overlay_weak     = "#42AED3"

# Background layers
bg_high             = "#475153"
bg_medium           = "#7A7E7D"
bg_low              = "#AFAFAF"
bg_subtle           = "#667886"
bg_deep             = "#899BB7"
