[default.variables]
#mako
mako_background = "@bg_medium"
mako_border = "#026374"
mako_low = "#39598A"
mako_normal = "#704998"
mako_high = "#CE0B43"
# GTK
gtk_accent           = "#465CA8"
gtk_error            = "#CE0B43"
gtk_success          = "#8DB324"
gtk_text             = "#111015"
gtk_bg_popup         = "#ABC929"
gtk_bg               = "#667886"
gtk_bg_destructive   = "#CE0B43"

# Statusline
prompt_normal_mode       = "#026374"
prompt_insert_mode       = "#465CA8"
prompt_visual_mode       = "#034F9E"
prompt_replacement_mode  = "#CE0B43"
prompt_unknown_mode      = "#EE5E85"
prompt_error             = "#CE0B43"
prompt_detached_branch   = "#034F9E"
prompt_branch            = "#026374"
prompt_commit            = "#465CA8"
prompt_action            = "#EE5E85"
prompt_ssh_host          = "#034F9E"
prompt_ssh_user          = "#465CA8"
prompt_venv              = "#026374"
prompt_user              = "#667886"
prompt_root              = "#CE0B43"
prompt_pwd               = "#39598A"

# Status icons
status_ahead             = "#465CA8"
status_behind            = "#CE0B43"
status_stashed           = "#034F9E"
status_added             = "#026374"
status_deleted           = "#CE0B43"
status_modified          = "#EE5E85"
status_renamed           = "#465CA8"
status_unmerged          = "#CE0B43"
status_untracked         = "#39598A"
foreground_text          = "#111015"

# Fish shell
color_autosuggestion           = "#465656"
color_command                  = "#465CA8"
color_comment                  = "#465656"
color_cwd                      = "#026374"
color_cwd_root                 = "#CE0B43"
color_end                      = "#EE5E85"
color_error                    = "#CE0B43"
color_escape                   = "#704998"
color_host                     = "#DAD650"
color_host_remote              = "#EE5E85"
color_normal                   = "#111015"
color_operator                 = "#034F9E"
color_param                    = "#EE5E85"
color_quote                    = "#026374"
color_redirection_color        = "#704998"
color_search_match_foreground  = "#667886"
color_search_match_background  = "#EE5E85"
color_selection_foreground     = "#667886"
color_selection_background     = "#DAD650"
color_status                   = "#CE0B43"
color_user                     = "#465CA8"
pager_color_completion         = "#111015"
pager_color_description_color  = "#465656"
pager_color_prefix_color       = "#DAD650"
pager_color_progress_background= "#ABC929"
pager_color_progress_foreground= "#111015"

# Niri
active-color   = "#465CA8"
inactive-color = "#503424"
urgent-color   = "#CE0B43"
shadow         = "#503424"

# Cursor
foreground = "#0196D5"
outline    = "#121116"
background = "#FFFFFF"

# SDDM / login
accent_warning   = "#EE5E85"
accent_info      = "#704998"
accent_primary   = "#0093D3"
accent_secondary = "#8DB324"
accent_light     = "#024F9D"
accent_hover     = "#31527D"
accent_alt       = "@accent_secondary@"
error       = "#E83D2B"
error_alt   = "#E83D2B"
warning     = "#EE5E85"
attention   = "#EE5E85"
success     = "#8DB324"
info        = "#704998"
link        = "#0093D3"

# Foreground layers
fg_primary         = "#6E4796"
fg_secondary       = "#4056A2"
fg_muted           = "#4157A3"
fg_overlay_strong  = "#006C6E"
fg_overlay_medium  = "#058F99"
fg_overlay_weak    = "#42AED3"

# Background layers
bg_surface_high    = "#475153"
bg_surface_medium  = "#7A7E7D"
bg_surface_low     = "#AFAFAF"
bg_base            = "#7A7E7D"
bg_subtle          = "#667886"
bg_deep            = "#899BB7"

