[gtk]
gtk_accent = "#89b4fa"
gtk_error = "#f38ba8"
gtk_success = "#a6e3a1"
gtk_text = "#cdd6f4"
gtk_bg_popup = "#313244"
gtk_bg = "#1e1e2e"
gtk_bg_destructive = "#f38ba8"

[fish_prompt]
prompt_normal_mode = "#a6e3a1"
prompt_insert_mode = "#89b4fa"
prompt_visual_mode = "#f5c2e7"
prompt_replacement_mode = "#f38ba8"
prompt_unknown_mode = "#f9e2af"
prompt_error = "#f38ba8"
prompt_detached_branch = "#f5c2e7"
prompt_branch = "#a6e3a1"
prompt_commit = "#89b4fa"
prompt_action = "#f9e2af"
prompt_ssh_host = "#f5c2e7"
prompt_ssh_user = "#89b4fa"
prompt_venv = "#a6e3a1"
prompt_user = "#cdd6f4"
prompt_root = "#f38ba8"
prompt_pwd = "#bac2de"

status_ahead = "#89b4fa"
status_behind = "#f38ba8"
status_stashed = "#f5c2e7"
status_added = "#a6e3a1"
status_deleted = "#f38ba8"
status_modified = "#f9e2af"
status_renamed = "#89b4fa"
status_unmerged = "#f38ba8"
status_untracked = "#bac2de"

foreground_text = "#cdd6f4"

[fish]
color_autosuggestion = "#6c7086"
color_command = "#89b4fa"
color_comment = "#7f849c"
color_cwd = "#a6e3a1"
color_cwd_root = "#f38ba8"
color_end = "#fab387"
color_error = "#f38ba8"
color_escape = "#94e2d5"
color_host = "#b4befe"
color_host_remote = "#f9e2af"
color_normal = "#cdd6f4"
color_operator = "#cba6f7"
color_param = "#f9e2af"
color_quote = "#a6e3a1"
color_redirection_color = "#74c7ec"
color_search_match_foreground = "#1e1e2e"
color_search_match_background = "#f9e2af"
color_selection_foreground = "#1e1e2e"
color_selection_background = "#b4befe"
color_status = "#f38ba8"
color_user = "#89b4fa"
pager_color_completion = "#cdd6f4"
pager_color_description_color = "#7f849c"
pager_color_prefix_color = "#b4befe"
pager_color_progress_background = "#313244"
pager_color_progress_foreground = "#cdd6f4"

[niri]
active-color = "#89b4fa"
inactive-color = "#6c7086"
urgent-color = "#f38ba8"
shadow = "#11111b"

[cursor]
foreground = "#cdd6f4"
outline = "#313244"
background = "#89b4fa"

[sddm]
accent_warning   = "#f9e2af"
accent_info      = "#89b4fa"
accent_primary   = "#89dceb"
accent_secondary = "#a6e3a1"
accent_light     = "#cdd6f4"
accent_hover     = "#cba6f7"
accent_alt       = "#fab387"

error       = "#f38ba8"
error_alt   = "#eba0ac"
warning     = "#f9e2af"
attention   = "#fab387"
success     = "#a6e3a1"
info        = "#89b4fa"
link        = "#89dceb"

fg_primary         = "#cdd6f4"
fg_secondary       = "#a6adc8"
fg_muted           = "#6c7086"
fg_overlay_strong  = "#585b70"
fg_overlay_medium  = "#45475a"
fg_overlay_weak    = "#313244"

bg_surface_high   = "#313244"
bg_surface_medium = "#1e1e2e"
bg_surface_low    = "#181825"
bg_base           = "#1e1e2e"
bg_subtle         = "#181825"
bg_deep           = "#11111b"

