[helpers]
no_hash = ".dotter/helpers/no_hash.rhai"
[default]
depends = []

[default.files]
config = "~/.config"
"theme/gtk/adw" ={target = "~/.themes/adw", type="symbolic"}
"git/gitconfig" = "~/.gitconfig"
"theme/icons" = {target = "~/.local/share/icons", type="symbolic"}
firefox = "~/.mozilla/firefox"
"theme/gtk/gtk.css" = "~/.config/gtk/gtk.css"

[default.variables]
user = "mees"
wallpaper = "~/dotfiles/theme/wallpaper.jpg"

[packages]

[settings]
default_target_type = "automatic"
