[helpers]

[default]
depends = []

[default.files]
#config = {target = "~/.config", type="symbolic"}
config = "~/.config"
"theme/gtk/adw" ="~/.themes/adw"
"git/gitconfig" = "~/.gitconfig"
"theme/icons" = {target = "~/.local/share/icons", type="symbolic"}
firefox = "~/.mozilla/firefox"
[default.variables]
user = "mees"
[settings]
default_target_type = "automatic"
