primary = "#ebbcba"
secondary = "#ebbcba"
tertiary = "#c4a7e7"

muted_primary = "#ea9a97"
muted_secondary = "#ea9a97"
muted_tertiary = "#c4a7e7"

warning = "#f6c177"
error = "#eb6f92"
info = "#9ccfd8"
text = "#e0def4"
subtext = "#575279"
inverse_text = "#575279"
highlight = "#ea9d34"
success = "#56949f"
hover = "#907aa9"

foreground = "#faf4ed"
muted_foreground= "#fffaf3"

background = "#191724"
muted_background= "#232136"

cursor_foreground = "#ebbcba"
cursor_background = "#ea9d34"
cursor_outline = "#524f67"
